#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
$opt     = getopt('v::');
$version = '';
if (array_key_exists('v', $opt)) {
    $version = $opt['v'];
    if (!preg_match('/^\d+\.\d+\.\d+(-[\d\w\.]+)?$/i', $version)) {
        die("Version number must follow semantic versioning.\n");
    }
}

$pharName = "oxrun.phar";
$pharFile = __DIR__ . '/' . $pharName;
if (file_exists($pharFile)) {
    unlink($pharFile);
}
$phar = new \Phar($pharFile, 0, $pharName);
$phar->setSignatureAlgorithm(\Phar::SHA1);
$phar->startBuffering();
$finder = new Symfony\Component\Finder\Finder();
$finder->files()
    ->ignoreVCS(true)
    ->name('*.php')
    ->name('*.json')
    ->name('*.exe')
    ->exclude('phpunit')
    ->exclude('Tests')
    ->exclude('test')
    ->exclude('tests')
    ->exclude('phpspec')
    ->notName('*.phar')
    ->notName('.travis.yml')
    ->notName('box.json')
    ->in(__DIR__);
foreach ($finder as $fileInfo) {
    $file = str_replace(__DIR__, '', $fileInfo->getRealPath());
    echo "Add file: " . $file . "\n";
    if($fileInfo->getExtension() === 'php'){
        $phar->addFromString($file, php_strip_whitespace($fileInfo->getRealPath()));
    } else {
        $phar->addFile($fileInfo->getRealPath(), $file);
    }
}
// Add bin/dep file
$depContent = file_get_contents(__DIR__ . '/bin/oxrun');
$depContent = str_replace("#!/usr/bin/env php\n", '', $depContent);
$depContent = str_replace("@package_version@", "$version", $depContent);
$depContent = str_replace('__FILE__', 'str_replace("phar://", "", Phar::running())', $depContent);
$phar->addFromString('bin/oxrun', $depContent);
$stub = <<<STUB
#!/usr/bin/env php
<?php
Phar::mapPhar('{$pharName}');
require 'phar://{$pharName}/bin/oxrun';
__HALT_COMPILER();
STUB;
$phar->setStub($stub);
// Bug #53467. Phar cannot compress large archives. https://bugs.php.net/bug.php?id=53467
// $phar->compressFiles(Phar::GZ);
$phar->stopBuffering();
unset($phar);
echo "$pharName was created successfully.\n";
